version: '3.8'

services:
  larapp:
    container_name: LarAPP_api
    build: 
      context: .
      dockerfile: LarAPP/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: LarAPP_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: LarAPP    
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
